name: 'Cache Docker Retry'
description: 'Retries the caching retrieval of docker images'
inputs:
  key:
    description: An explicit key for restoring and saving the cache
    required: true
    default: docker-layer-caching-${{ github.workflow }}-{hash}
  restore-keys:
    description: An ordered list of keys to use for restoring the cache if no cache hit occurred for key
    required: false
    default: docker-layer-caching-${{ github.workflow }}-
  skip-save:
    description: Skip saving layers in the post step
    required: false
    default: 'false'
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Docker images caching - try 1
      id: dock1
      continue-on-error: true
      uses: jpribyl/action-docker-layer-caching@v0.1.1
      with:
        key: ${{ inputs.key }}
        restore-keys: ${{ inputs.restore-keys }}
        skip-save: ${{ inputs.skip-save }}
    - name: retry-sleep-1
      if: ${{ always() && steps.dock1.outcome == 'failure' }} # the first condition (always) is needed for how status check functions works in GitHub actions (see https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions)
      run: sleep 30
      shell: bash
    - name: Docker images caching - try 2
      if: ${{ always() && steps.dock1.outcome == 'failure' }} #NOTE : this failure test could be replaced by a counting of kapua images in the environment. TODO if this check don't work on failure
      id: dock2
      continue-on-error: true
      uses: jpribyl/action-docker-layer-caching@v0.1.1
      with:
        key: ${{ inputs.key }}
        restore-keys: ${{ inputs.restore-keys }}
        skip-save: ${{ inputs.skip-save }}
    - name: retry-sleep-2
      if: ${{ always() && steps.dock2.outcome == 'failure' }}
      run: sleep 60
      shell: bash
    - name: Docker images caching - try 3
      if: ${{ always() && steps.dock2.outcome == 'failure' }}
      continue-on-error: false
      id: dock3
      uses: jpribyl/action-docker-layer-caching@v0.1.1
      with:
        key: ${{ inputs.key }}
        restore-keys: ${{ inputs.restore-keys }}
        skip-save: ${{ inputs.skip-save }}