openapi: 3.0.3

info:
  title: Everyware Cloud REST API - User Credentials
  version: '1.0'
  contact:
    name: Eurotech
    url: https://www.eurotech.com


paths:
  /{scopeId}/user/mfa:
    get:
      tags:
        - User - Mfa
      summary: Get the MfaOption of this User
      operationId: mfaOptionGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
      responses:
        200:
          description: The details of the desired MfaOption
          content:
            application/json:
              schema:
                $ref: '../userMfa/userMfa.yaml#/components/schemas/mfaOption'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    post:
      tags:
        - User - Mfa
      summary: Activates MFA for the current user
      operationId: mfaOptionCreate
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
      responses:
        201:
          description: The MfaOption that has just been created
          content:
            application/json:
              schema:
                $ref: '../userMfa/userMfa.yaml#/components/schemas/mfaOptionCreationResponse'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    delete:
      tags:
        - User - Mfa
      summary: Delete a single MfaOption
      operationId: mfaOptionDelete
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
      responses:
        204:
          description: The MfaOption has been deleted
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'