openapi: 3.0.3

info:
  title: Everyware Cloud REST API - User Mfa
  version: '1.0'
  contact:
    name: Eurotech
    url: https://www.eurotech.com

paths: { }

components:
  schemas:
    mfaOption:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaUpdatableEntity'
        - description: An object containing all the information for a single MfaOption
          type: object
          properties:
            userId:
              allOf:
                - $ref: '../openapi.yaml#/components/schemas/kapuaId'
            trustKey:
              description: |
                The key of the trusted machine.
              type: string
            trustExpirationDate:
              description: |
                The moment when the machine trust will expire.
              type: string
              format: 'date-time'
          example:
            $ref: '#/components/examples/mfaOption/value'
    mfaOptionCreator:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaUpdatableEntityCreator'
        - type: object
  examples:
    mfaOption:
      value:
        type: mfaOption
        id: "Tu4UpgmN0A4"
        scopeId: "AQ"
        createdOn: "2021-05-12T08:04:21.962Z"
        createdBy: "AQ"
        modifiedOn: "2021-05-12T08:04:21.962Z"
        modifiedBy: "AQ"
        optlock: 1,
        userId: "AQ"
        trustKey: "exampleTrustKey"
        trustExpirationDate: '2020-31-12T00:00:00.000Z'