name: pr-number-uploader
on: [pull_request] # Triggers the workflow on pull request events

#this workflow is used for the sonarCloud scan.
#It saves into an artifact the pull request number.
#In this way, then, the sonarCloud workflow (which is executed externally with respect to the context of the pr) retrieves it and performs the scan

jobs:
  uploader:
      runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
      - name: Save PR number to file for the sonarCloud scan
        run: echo ${{ github.event.number }} > PR_NUMBER.txt
      - name: Archive PR number
        uses: actions/upload-artifact@v3
        with:
          name: PR_NUMBER
          path: PR_NUMBER.txt
